carts/urls.py
from django.conf.urls import url

from .views import (
        cart_home,
        cart_update,
        checkout_home,
        checkout_done_view
        )



urlpatterns = [
	
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', cart_update, name='update'),
   
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

from accounts.views import login_page, register_page, guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from .view import home_page, about_page, contact_page




urlpatterns = [
	url(r'^$', home_page, name='home'),
	url(r'^about-us/$', about_page, name='about'),
	url(r'^login/$', login_page, name='login'),
    url(r'^register/guest$', guest_register_view, name='guest_register'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^register/$', register_page, name='register'),
	url(r'^contact-us/$', contact_page, name='contact'),
    url(r'^bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),
        
  
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns= urlpatterns + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    urlpatterns= urlpatterns + static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

carts/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed

from products.models import Product


User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated() and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated():
                user_obj = user
        return self.model.objects.create(user=user_obj)

class Cart(models.Model):
    user        = models.ForeignKey(User, null=True, blank=True)
    products    = models.ManyToManyField(Product, blank=True)
    subtotal    = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total       = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)




def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)




def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.08) 
    else:
        instance.total = 0.00 #* 1.08

pre_save.connect(pre_save_cart_receiver, sender=Cart)

carts/views.py
from django.shortcuts import render, redirect

from accounts.forms import LoginForm, GuestForm
from accounts.models import GuestEmail
from addresses.forms import AddressForm
from addresses.models import Address
from billing.models import BillingProfile
from orders.models import Order
from products.models import Product
from .models import Cart

def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    # products = cart_obj.products.all()
    # total = 0
    # for x in products:
    #     total += x.price
    # print(total)
    # cart_obj.total = total
    # cart_obj.save()
    return render(request, "carts/home.html", {"cart":cart_obj})

def cart_update(request):
    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj = Product.object.get(id=product_id)
        except Product.DoesNotExist:
            print("Show messge to user Product has gone")
            return redirect("cart:home")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
                cart_obj.products.remove(product_id)
        else:
            cart_obj.products.add(product_obj)
        request.session['cart_items'] = cart_obj.products.count()
    return redirect("cart:home")

# def checkout_home(request):
#     cart_obj, cart_created = Cart.objects.new_or_get(request)
#     order_obj = None
#     if cart_created or cart_obj.products.count
#         return redirect("cart:home")
#     else:
#         order_obj, new_order_obj = Order
#     return(request, "carts/checkout.html", {})
def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("cart:home")

    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()
    billing_address_form = AddressForm()
    billing_address_id = request.session.get("billing_address_id", None)
    shipping_address_id = request.session.get("shipping_address_id", None)

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    address_qs = None
    if billing_profile is not None:
        address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session["shipping_address_id"]
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id)
            del request.session["billing_address_id"]
        if billing_address_id or shipping_address_id:
            order_obj.save()
    if request.method == "POST":
        "SOME CHECK THAT ORDER HAS DONE"
        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            request.session['cart_items'] = 0
            del request.session['cart_id']
            return redirect("cart:success")    
            
    context = {
        "object": order_obj,
        "billing_profile": billing_profile,
        "login_form": login_form,
        "guest_form":guest_form,
        "address_form":address_form,
        "billing_address_form":billing_address_form,
        "address_qs":address_qs
    }
    return render(request, "carts/checkout.html", context )


def checkout_done_view(request):
    return render(request, "carts/checkout-done.html", {})

carts/templates/carts/checkout-done.html
{% extends "base.html" %}


{% block content %}
<div class='col-6 mx-auto py-5 text-center'>
  <h1 class='display-1'>Thank you for your order!!!</h1>
</div>

{% endblock %}

carts/templates/carts/checkout.html
{% extends "base.html" %}


{% block content %}
{% if not billing_profile %}
    <div class='row text-center'>
    <div class='col-12 col-md-6'>
        <p class='lead'>Login</p>
        {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
    </div>
    <div class='col-12 col-md-6'> 
        Continue as Guest

        {% url "guest_register" as guest_register_url %}
        {% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
    </div>

    </div>

{% else %}
            
        {% if not object.shipping_address %}

         <div class='row'>
            <div class='col-12'>
                <p class='lead'>Shipping Address</p>
                <hr/>
            </div>
            <div class='col-6'>
                

           

                    {% url "checkout_address_create" as checkout_address_create %}
                    {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}'



             </div>
         <div class='col-6'>
            {% url 'checkout_address_reuse' as checkout_address_reuse %}
            {% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='shipping' action_url=checkout_address_reuse %}
            </div>
        </div>


        {% elif not object.billing_address %}
        <div class='row'>
            <div class='col-12'>
                 <p class='lead'>Billing Address</p>
                <hr/>
            </div>
            <div class='col-6'>
               
            {% url "checkout_address_create" as checkout_address_create %}
            {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='billing' %}
            </div>
              <div class='col-6'>
                {% url 'checkout_address_reuse' as checkout_address_reuse %}
             {% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri  address_type='billing' action_url=checkout_address_reuse %}
         </div>

         
        </div>
        {% else %}

        <h1>Finalize Checkout</h1>
        <p>Cart Items: {% for product in object.cart.products.all %}{{ product }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
        <p>Shipping Address: {{ object.shipping_address.get_address }}</p>
        <p>Billing Address: {{ object.shipping_address.get_address }}</p>
        <p>Cart Total: {{ object.cart.total }}</p>
        <p>Shipping Total: {{ object.shipping_total }}</p>
        <p>Order Total: {{ object.total }}</p>
        <form class='form' method='POST' action="">{% csrf_token %}
            <button type='submit' class='btn btn-success'>Checkout</button>
        </form>
        {% endif %}
{% endif %}



{% endblock %}

carts/templates/carts/home.html
{% extends "base.html" %}




{% block content %}
<h1>Cart</h1>

{% if cart.products.exists %}
<div class="container">
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Product Name</th>
        <th scope="col">Product Price</th>
      </tr>
    </thead>
    <tbody>
      {% for product in cart.products.all %}  
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        
        <td><a href='{{ product.get_absolute_url }}'>{{ product.title }}</a> 
            {% include 'products/snippets/update-cart.html' with product=product cart=cart in_cart=True %}
        </td>
        <td>{{ product.price }}</td>
      </tr>
      <tr>
      {% endfor %}
        <td colspan="2"></td>   
        <td><b>Subtotal</b> {{ cart.subtotal }}</td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td><b>Total</b> {{ cart.total }}</td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td><a class='btn  btn-success' href='{% url "cart:checkout" %}'>Checkout</a></td>
      </tr>
    </tbody>
</table>
</div>
{% else %}

<p class="lead">Actually Cart is Empty</p>
{% endif%}

{% endblock %}